name: top_back
description: "project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.2.1
  dio: ^5.7.0
  logger: ^2.5.0
  bot_toast: ^4.1.3
  encrypt: ^5.0.3
  shared_preferences: ^2.3.4
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  country_picker: ^2.0.27
  board_datetime_picker: ^2.1.6
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_video_thumbnail_plus: ^1.0.5
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/